# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 135)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(737, 135))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(737, 135))
        self.centralwidget.setMaximumSize(QtCore.QSize(737, 135))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(4, 59, 731, 38))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.sendButton = QtWidgets.QPushButton(self.widget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.configButton = QtWidgets.QToolButton(self.widget)
        self.configButton.setObjectName("configButton")
        self.horizontalLayout.addWidget(self.configButton)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(4, 10, 731, 38))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.audioPrevButton = QtWidgets.QToolButton(self.widget1)
        self.audioPrevButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.audioPrevButton.setObjectName("audioPrevButton")
        self.horizontalLayout_2.addWidget(self.audioPrevButton)
        self.audioPauseButton = QtWidgets.QToolButton(self.widget1)
        self.audioPauseButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.audioPauseButton.setObjectName("audioPauseButton")
        self.horizontalLayout_2.addWidget(self.audioPauseButton)
        self.audioPlayButton = QtWidgets.QToolButton(self.widget1)
        self.audioPlayButton.setMaximumSize(QtCore.QSize(32, 16777215))
        self.audioPlayButton.setObjectName("audioPlayButton")
        self.horizontalLayout_2.addWidget(self.audioPlayButton)
        self.audioNextButton = QtWidgets.QToolButton(self.widget1)
        self.audioNextButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.audioNextButton.setObjectName("audioNextButton")
        self.horizontalLayout_2.addWidget(self.audioNextButton)
        self.customButton1 = QtWidgets.QPushButton(self.widget1)
        self.customButton1.setObjectName("customButton1")
        self.horizontalLayout_2.addWidget(self.customButton1)
        self.customButton2 = QtWidgets.QPushButton(self.widget1)
        self.customButton2.setObjectName("customButton2")
        self.horizontalLayout_2.addWidget(self.customButton2)
        self.customButton3 = QtWidgets.QPushButton(self.widget1)
        self.customButton3.setObjectName("customButton3")
        self.horizontalLayout_2.addWidget(self.customButton3)
        self.customButton4 = QtWidgets.QPushButton(self.widget1)
        self.customButton4.setObjectName("customButton4")
        self.horizontalLayout_2.addWidget(self.customButton4)
        self.customButton5 = QtWidgets.QPushButton(self.widget1)
        self.customButton5.setObjectName("customButton5")
        self.horizontalLayout_2.addWidget(self.customButton5)
        self.customButton6 = QtWidgets.QPushButton(self.widget1)
        self.customButton6.setObjectName("customButton6")
        self.horizontalLayout_2.addWidget(self.customButton6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mycroft AI Panel"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.configButton.setText(_translate("MainWindow", "..."))
        self.audioPrevButton.setText(_translate("MainWindow", "<<"))
        self.audioPauseButton.setText(_translate("MainWindow", "||"))
        self.audioPlayButton.setText(_translate("MainWindow", ">"))
        self.audioNextButton.setText(_translate("MainWindow", ">>"))
        self.customButton1.setText(_translate("MainWindow", "Custom1"))
        self.customButton2.setText(_translate("MainWindow", "Custom2"))
        self.customButton3.setText(_translate("MainWindow", "Custom3"))
        self.customButton4.setText(_translate("MainWindow", "Custom4"))
        self.customButton5.setText(_translate("MainWindow", "Custom5"))
        self.customButton6.setText(_translate("MainWindow", "Custom6"))


